# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='massage',
            new_name='msg',
        ),
    ]
